# Generated by Django 6.0.3 on 2026-04-03 02:55

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0005_promptmessage_rarity")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="report_channel_id",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="Discord channel ID inside the report server where reports will be posted.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="report_guild_id",
            field=models.BigIntegerField(
                blank=True, default=None, help_text="Discord server ID where user reports will be sent.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="admin_channel_ids",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Semicolon-delimited channel IDs where staff may bypass inventory "
                    "privacy. Ignored for owners. If empty, then admin commands can be "
                    "used everywhere."
                ),
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^(\\d{17,21}(;\\d{17,21})*)?$"), message="The IDs must be semicolon-separated"
                    )
                ],
            ),
        ),
    ]
