# Generated by Django 6.0.3 on 2026-04-02 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more")]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_id", models.CharField(help_text="Unique report identifier", max_length=6, unique=True)),
                ("user_id", models.BigIntegerField(help_text="Discord user ID who filed the report")),
                ("user_name", models.CharField(help_text="Discord username at time of report", max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("violation", "Report Violation"),
                            ("bug", "Report Bug"),
                            ("suggestion", "Provide Suggestion"),
                            ("other", "Other"),
                        ],
                        help_text="Type of report submitted",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Report content/description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("replied", models.BooleanField(default=False, help_text="Whether this report has been replied to")),
                ("reply_content", models.TextField(blank=True, help_text="Administrator reply content", null=True)),
                (
                    "reply_by",
                    models.CharField(blank=True, help_text="Administrator who replied", max_length=255, null=True),
                ),
                ("reply_time", models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={"db_table": "report", "ordering": ["-created_at"], "managed": True},
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="server_id",
            field=models.BigIntegerField(
                blank=True, help_text="Discord server ID where this ball was caught", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance", name="spawned_time", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="special",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.special"
            ),
        ),
        migrations.AlterField(
            model_name="ballinstance",
            name="trade_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ballinstance_trade_player_set",
                to="bd_models.player",
            ),
        ),
    ]
