# Generated by Django 6.0.3 on 2026-04-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0015_report_model")]

    operations = [
        migrations.CreateModel(
            name="RarityTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Display name of the tier (e.g. Legendary)", max_length=64, unique=True),
                ),
                ("emoji", models.CharField(help_text="Emoji shown next to the tier name (e.g. 🔴)", max_length=8)),
                (
                    "color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Hex color code used for display purposes (e.g. #FFD700)",
                        max_length=7,
                    ),
                ),
                (
                    "min_percentile",
                    models.FloatField(
                        help_text=(
                            "Minimum rarity percentile for a collectible to qualify for this tier. "
                            "Uses a 0.0–1.0 scale where 1.0 is the rarest end and 0.0 is the most common. "
                            "Tiers are evaluated from highest to lowest; the first match wins."
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "Rarity Tier",
                "verbose_name_plural": "Rarity Tiers",
                "db_table": "raritytier",
                "ordering": ["-min_percentile"],
                "managed": True,
            },
        )
    ]
